title: Imen Ayadi
description: Applied Mathematics â€“ Statistics, Riemannian Geometry, Signal Processing

theme: minima

header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
