title: Imen Ayadi
description: This website uses Google Analytics for anonymous usage statistics.

theme: minima

header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
